### Numpy

In [1]:
import numpy as np

In [11]:
ls = [[1,2,3,4,5,6,7]]
arr = np.array(ls)
print(type(ls))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
arr.ndim

2

In [13]:
arr.shape

(1, 7)

In [14]:
l = [[1,1.2,3,4,4.5],[1,2,5,4.9,6.7]]
arr = np.array(l)

In [15]:
arr

array([[1. , 1.2, 3. , 4. , 4.5],
       [1. , 2. , 5. , 4.9, 6.7]])

In [19]:
arr.dtype

dtype('float64')

In [20]:
l1 = [[1,2,'bsk'],[1,2.5,'0']]
arr = np.array(l1)
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
<U32


In [25]:
np.array([12,33,46,2.5,4+3j],dtype=str)

array(['12', '33', '46', '2.5', '(4+3j)'], dtype='<U6')

In [29]:
ls1 = [[[1,2,3],[4,5,6]],[[7,8,9],[8,7,6]],[[1,2,3],[4,5,6]],[[7,8,9],[8,7,6]]]
arr = np.array(ls1)
print(type(arr))
print(arr.shape)
print(arr.ndim)

<class 'numpy.ndarray'>
(4, 2, 3)
3


In [28]:
arr.size

24

In [32]:
np.array([[1,2,3],[4,5,6],[7,8,None]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, None]], dtype=object)

In [36]:
np.array([[1,2,3],[4,5,6],[7,8,np.nan]])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., nan]])

In [42]:
# ls = list(range(1.5,11.5))
ls = np.arange(1.5,11.5,0.5)
ls

array([ 1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,
        7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ])

In [44]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [48]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [49]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9])

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [60]:
ones = np.ones([2,3,4],dtype=int)
ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [62]:
ones.ndim

3

In [65]:
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [64]:
np.full([2,5],7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.full([2,3],[7,8,9])


array([[7, 8, 9],
       [7, 8, 9]])

In [76]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [77]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [82]:
np.random.randint(1,10,[5,4])

array([[3, 5, 3, 3],
       [5, 3, 8, 1],
       [6, 1, 6, 7],
       [3, 1, 6, 8],
       [6, 5, 2, 9]], dtype=int32)

In [84]:
np.random.rand(1,10,5)

array([[[0.57719631, 0.59217594, 0.37634069, 0.65959277, 0.48361065],
        [0.87688735, 0.24491147, 0.72991115, 0.37893448, 0.02341243],
        [0.1833114 , 0.24461981, 0.26228832, 0.73711353, 0.76555804],
        [0.94088939, 0.76022706, 0.21849455, 0.29971706, 0.72768619],
        [0.59257542, 0.61675151, 0.27927115, 0.62287413, 0.59922845],
        [0.47118084, 0.67658167, 0.68347714, 0.53859725, 0.81804243],
        [0.32451778, 0.59319188, 0.16959672, 0.06765175, 0.49053041],
        [0.11345511, 0.14204806, 0.42197041, 0.61577681, 0.37001952],
        [0.8513847 , 0.53731485, 0.31769382, 0.91036419, 0.24045024],
        [0.32921682, 0.41853184, 0.01318231, 0.7155842 , 0.14147361]]])

In [85]:
np.random.randn(5)

array([ 1.51194406,  2.34795078, -1.44854842,  0.15508976, -1.64596563])

In [87]:
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

In [ ]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [91]:
np.linspace(2,5,retstep=True,)

(array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
        2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
        2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
        2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
        3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
        3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
        3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
        4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
        4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
        4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ]),
 np.float64(0.061224489795918366))

In [92]:
arr = np.arange(1,11).reshape([2,5])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### **Copy and view**

In [93]:
new_arr = arr.view()
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [94]:
arr[0][0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [95]:
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [99]:
new_arr[0][1] = 23
new_arr

array([[100,  23,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [100]:
arr

array([[100,  23,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [96]:
new_arr2 = arr.copy()
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [97]:
new_arr2[00][0] = 1000
new_arr2

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [98]:
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [101]:
new_arr.transpose()

array([[100,   6],
       [ 23,   7],
       [  3,   8],
       [  4,   9],
       [  5,  10]])